export let arrayCars = [
    {id: 1,
      brand: 'honda',
      model: 'sivic',
      year: 1998,
      power: 1400,
      color: 'blue'},
    {id: 2,
      brand: 'honda',
      model: 'acord',
      year: 2005,
      power: 2000,
      color: 'black'},
    { id: 3,
      brand: 'volkswagen',
      model: 'pasat',
      year: 2008,
      power: 2000,
      color: 'blue'},
    { id: 4,
      brand: 'volkswagen',
      model: 'golf',
      year: 1998,
      power: 1400,
      color: 'blue'},
    {id: 5,
      brand: 'volkswagen',
      model: 'tiguan',
      year: 2010,
      power: 3000,
      color: 'green'},
    {id: 6,
      brand: 'volkswagen',
      model: 'toareg',
      year: 1998,
      power: 2000,
      color: 'red'},
    {id: 7,
      brand: 'volkswagen',
      model: 'polo',
      year: 2007,
      power: 1800,
      color: 'yellow'},
    {id: 8,
      brand: 'volkswagen',
      model: 'jetta',
      year: 2015,
      power: 2000,
      color: 'orange'},
    {id: 9,
      brand: 'volkswagen',
      model: 'caddy',
      year: 2004,
      power: 2000,
      color: 'black'}
  ]
;
